# netlify.toml

[[headers]]
  for = "/processed_images/*"
    [headers.values]
      cache-control = "public,max-age=360000"
[[headers]]
  for = "/css/*"
    [headers.values]
      cache-control = "public,max-age=360000"
[[headers]]
  for = "/js/*"
    [headers.values]
      cache-control = "public,max-age=360000"
