[[plugins]]
package = "@netlify/plugin-local-install-core"
[[plugins]]
package = "./netlify-plugin-image-optim"
[[plugins]]
package = "netlify-plugin-minify-html"
[[plugins]]
package = "netlify-plugin-hashfiles"
